### ISSUE TITLE
doesn't work for me

### ISSUE THREAD

**Issue by FLemon** [simongfxu/giab#1]
I got `2 blog posts have been inserted to /Users/jinxie/Documents/docs/work/Projects/Personal/blog/README.md`

but not thing is inserted, can you help ?

here's my repo: https://github.com/FLemon/FLemon.github.io
and heres my `.giabrc`

```
{
  "type": "basic",
  "username": "flemon",
  "password": "xxx",
  "issues": {
    "repo": "flemon.github.io",
    "owner": "flemon"
  }
}
```

**Comment by SiZapPaaiGwat** [comment]
Insert this code to your README.md

``` html
<!--giab:issue_list_start-->
your articles will be shown here
<!--giab:issue_list_end-->
```

You can put it anywhere you want.

**Comment by FLemon** [comment]
ah, right, thank you, I thought i had them, for some reason lost them during the commit
